### ISSUE TITLE
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fd1b85757b8>

### ISSUE THREAD

**Issue by yyangmei** [speedinghzl/CCNet#14]
When I run run_local.sh, I get the problem as followed. How can I solve it? Thanks.
`Traceback (most recent call last):
  File "train.py", line 249, in <module>
    main()
  File "train.py", line 212, in main
    preds = model(images, args.recurrence)
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 114, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/parallel/data_parallel.py", line 124, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 65, in parallel_apply
    raise output
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/parallel/parallel_apply.py", line 41, in _worker
    output = module(*input, **kwargs)
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ym/CCNet/networks/ccnet.py", line 196, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/ym/anaconda3/envs/py3.5_pytorch0.4.0/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ym/CCNet/libs/bn.py", line 184, in forward
    self.activation, self.slope)
  File "/home/ym/CCNet/libs/functions.py", line 183, in forward
    _check(_ext.bn_mean_var_cuda, x, mean, var)
  File "/home/ym/CCNet/libs/functions.py", line 16, in _check
    raise RuntimeError("CUDA Error encountered in {}".format(fn))
RuntimeError: CUDA Error encountered in <function CompiledLib.bn_mean_var_cuda at 0x7fd1b85757b8>
`

**Comment by yyangmei** [comment]
I only want to use 1 or 2 gpus, is that because of gpu number?

**Comment by speedinghzl** [comment]
It's ok to just use 1 or 2 gpus.
Have you compiled Inplace-abn or criss-cross attention with the correct arch. Please refer to [here](https://github.com/speedinghzl/CCNet#compiling).
