### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by vdsprakash** [speedinghzl/CCNet#22]
ImportError: /home/denny/github_open_Sources/CCNet/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

Complete Traceback:-

Traceback (most recent call last):
  File "evaluate.py", line 14, in <module>
    from networks.ccnet import Res_Deeplab
  File "/home/denny/github_open_Sources/CCNet/networks/ccnet.py", line 15, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/denny/github_open_Sources/CCNet/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/denny/github_open_Sources/CCNet/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/denny/github_open_Sources/CCNet/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/denny/github_open_Sources/CCNet/libs/_ext/__init__.py", line 3, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ImportError: /home/denny/github_open_Sources/CCNet/libs/_ext/__ext.so: undefined symbol: __cudaPopCallConfiguration

**Comment by speedinghzl** [comment]
Could you please provide your cuda version? Have you compiled the Inplace-ABN before?
