### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Kobeee0614** [speedinghzl/CCNet#25]
Hello, the GPU I am using is TITAN XP, batch_size=2, other parameters are the same as yours, why can't I run it?`/home/jason/.local/lib/python3.5/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
121975 images are loaded!
/home/jason/.local/lib/python3.5/site-packages/torch/nn/functional.py:1890: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
iter = 0 of 60000 completed, loss = 4.349814414978027
taking snapshot ...
Traceback (most recent call last):
  File "train.py", line 313, in <module>
    main()
  File "train.py", line 276, in main
    loss.backward()
  File "/home/jason/.local/lib/python3.5/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jason/.local/lib/python3.5/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA error: out of memory
`

**Comment by speedinghzl** [comment]
please try to decrease input size from 769 to 713.
