### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by tong1101** [speedinghzl/CCNet#34]
AttributeError: Traceback (most recent call last):
  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ydc/anaconda3/envs/tl_pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/ydc/tl/pytorch/CCNet-master/dataset/datasets.py", line 178, in __getitem__
    size = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

HOW TO SOLVE IT?

**Comment by speedinghzl** [comment]
Please check your cityscape image and label paths are accessible.

**Comment by tong1101** [comment]
@speedinghzl I check it and I still can't solve the problem

**Comment by swjtulinxi** [comment]
i have the same problem

**Comment by Wj8066** [comment]
> 
> 
> i have the same problem

How is it going on about the problem? I have the same problem.

**Comment by fan-lucky** [comment]
![image](https://user-images.githubusercontent.com/71860113/180133927-28241ec3-09c7-4264-98ef-e199c2127058.png)I have problem about Nonetype，and am looking forward to your reply!

**Comment by tong1101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fan-lucky** [comment]
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 213, in main
    images, labels, _, _ = dataloader.next()
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/CCNet-pure-python/dataset/datasets.py", line 177, in __getitem__
    label = self.id2trainId(label)
  File "/root/CCNet-pure-python/dataset/datasets.py", line 164, in id2trainId
    label_copy = label.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

I have problem about Nonetype，and am looking forward to your reply!

**Comment by tong1101** [comment]
Sorry, I don't do related work anymore


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "speedinghzl/CCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 中午1:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [speedinghzl/CCNet] AttributeError: 'NoneType' object has no attribute 'shape' (#34)





 
Traceback (most recent call last):
 File "train.py", line 245, in 
 main()
 File "train.py", line 213, in main
 images, labels, _, _ = dataloader.next()
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in next
 data = self._next_data()
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
 return self._process_data(data)
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
 data.reraise()
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/_utils.py", line 461, in reraise
 raise exception
 AttributeError: Caught AttributeError in DataLoader worker process 0.
 Original Traceback (most recent call last):
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
 data = fetcher.fetch(index)
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/root/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in 
 data = [self.dataset[idx] for idx in possibly_batched_index]
 File "/root/CCNet-pure-python/dataset/datasets.py", line 177, in getitem
 label = self.id2trainId(label)
 File "/root/CCNet-pure-python/dataset/datasets.py", line 164, in id2trainId
 label_copy = label.copy()
 AttributeError: 'NoneType' object has no attribute 'copy'
 
I have problem about Nonetype，and am looking forward to your reply!

**Comment by tong1101** [comment]
Sorry, I don't do related work anymore




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "speedinghzl/CCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月21日(星期四) 中午1:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [speedinghzl/CCNet] AttributeError: 'NoneType' object has no attribute 'shape' (#34)





 
I have problem about Nonetype，and am looking forward to your reply!
