### ISSUE TITLE
dataset loading error for cityscapes

### ISSUE THREAD

**Issue by amiltonwong** [speedinghzl/CCNet#40]
Hi, @speedinghzl ,

Here is my command for training:
`python train.py --data-dir /media/root/WDdata/dataset/cityscapes_dataset/leftImg8bit_trainvaltest --random-mirror --random-scale --restore-from ./dataset/resnet101-imagenet.pth --gpu 0,1,2,3 --learning-rate 1e-2 --input-size 769,769 --weight-decay 1e-4 --batch-size 8 --num-steps 60000 --recurrence 2`

But the error shows that annotation labels are missing. 

```
481950 images are loaded!
Traceback (most recent call last):
  File "train.py", line 245, in <module>
    main()
  File "train.py", line 198, in main
    for i_iter, batch in enumerate(trainloader):
  File "/root/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/root/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/anaconda3/envs/pytorch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/data/code9/CCNet/dataset/datasets.py", line 177, in __getitem__
    label = self.id2trainId(label)
  File "/data/code9/CCNet/dataset/datasets.py", line 164, in id2trainId
    label_copy = label.copy()
AttributeError: 'NoneType' object has no attribute 'copy'

```

Could you elaborate on the directory structure for cityscapes dataset? e.g. the location on  img and labels.

THX!

**Comment by speedinghzl** [comment]
Hi @amiltonwong, the directory structure information could be found from the [train.lst](https://github.com/speedinghzl/CCNet/blob/master/dataset/list/cityscapes/train.lst).
