### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by yangninghua** [speedinghzl/CCNet#44]
```
[00:00<?,?it/s]12 15:10:26 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "evaluate.py", line 284, in <module>
    main()
  File "evaluate.py", line 247, in main
    output = predict_multiscale(model, image, input_size, [1.0], args.num_classes, False, 0)
  File "evaluate.py", line 168, in predict_multiscale
    scaled_probs = predict_sliding(net, scale_image, tile_size, classes, recurrence)
  File "evaluate.py", line 130, in predict_sliding
    padded_prediction = net(torch.from_numpy(padded_img).cuda(non_blocking=True))
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/spple/paddle/DeepGlint/CCNet-pytorch-1.1/networks/ccnet.py", line 176, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/inplace_abn-1.0.7-py3.6-linux-x86_64.egg/inplace_abn/abn.py", line 152, in forward
    self.activation, self.activation_param, self.group)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/inplace_abn-1.0.7-py3.6-linux-x86_64.egg/inplace_abn/functions.py", line 157, in inplace_abn_sync
    training, momentum, eps, activation, activation_param, group)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/inplace_abn-1.0.7-py3.6-linux-x86_64.egg/inplace_abn/functions.py", line 72, in forward
    ctx.world_size = distributed.get_world_size(group=group)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/home/spple/anaconda3/envs/pytorch1_1_0--py3_6--cuda9_0/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
```

**Comment by yenpengsun** [comment]
@yangninghua  I have the same problem. Have you solved this problem?

**Comment by yangninghua** [comment]
no,I have given up it




On 10/20/2019 15:38, xiaoxiao wrote:

@yangninghua I have the same problem. Have you solved this problem?

**Comment by cauivy** [comment]
@speedinghzl @yangninghua @yenpengsun I also got the problem mentioned above "AssertionError: Default process group is not initialized". Do you guys have any idea about this?

@yangninghua "gave it up" means you did not manage to run this project?

Thank you in advance!
