### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by Shumin0107** [speedinghzl/CCNet#82]
I have got the error below, how can i fix it?

[00:00<?,?it/s]17 08:33:48 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "train.py", line 251, in <module>
    main()
  File "train.py", line 226, in main
    loss = model(images, labels)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 152, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 162, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/zmz/ccnet/networks/ccnet.py", line 189, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/inplace_abn-1.1.0-py3.6-linux-x86_64.egg/inplace_abn/abn.py", line 323, in forward
    self.group,
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/inplace_abn-1.1.0-py3.6-linux-x86_64.egg/inplace_abn/functions.py", line 307, in inplace_abn_sync
    group,
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/inplace_abn-1.1.0-py3.6-linux-x86_64.egg/inplace_abn/functions.py", line 91, in forward
    ctx.world_size = distributed.get_world_size(group=group)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/usr/local/miniconda3/envs/dl10/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized

**Comment by jqc8438** [comment]
I have the same problem. Have you solved this problem?

**Comment by Shumin0107** [comment]
No, I just give up it, sori~

**Comment by sreeragh-ar** [comment]
This may be beacuse inplace-abn does not support single GPU.
If you have specified number of GPUs as 1 i.e, 
`--nproc_per_node=1`
please try changing it.
Reference: https://github.com/speedinghzl/CCNet/issues/88#issuecomment-731197639

**Comment by jqc8438** [comment]
> @jqc8438
> This may be because inplace-abn does not support single GPU.
> If you have specified number of GPUs as 1 i.e,
> `--nproc_per_node=1`
> please try changing it.
> Reference: [#88 (comment)](https://github.com/speedinghzl/CCNet/issues/88#issuecomment-731197639)

thank you,  actually, i set nproc_per_node=4
