### ISSUE TITLE
Error evualuating with only one GPU

### ISSUE THREAD

**Issue by gruossomonica** [speedinghzl/CCNet#88]
Hi, 
thanks for your work. Can I perform the evaluation of your pre-trained network using only one GPU? 
I test the Pytorch 1.1 implementation installing all requirements in a miniconda environment. I used cuda 10.0. I installed Apex using conda and Inplace-ABN with `pip install inplace-abn` (as indicated here: https://github.com/mapillary/inplace_abn)
I tried changing the `run_local.sh` file as the following:
```
#!/bin/bash
uname -a
#date
#env
date

GPU_IDS=0,1,2,3

CUDA_VISIBLE_DEVICES=${GPU_IDS} python -m torch.distributed.launch --nproc_per_node=1 evaluate.py --data-dir /media/monica/DATA/documenti/Monica/datasetOnline/cityscapes/ --model ccnet --input-size 769,769 --batch-size 4 --restore-from snapshots/CS_scenes_60000-r1-77.9.pth --gpu 0
```

But I got the following error:
```
Detected CUDA files, patching ldflags
Emitting ninja build file /media/monica/DATA/documenti/Monica/vos_approaches/CCNet/cc_attention/build/build.ninja...
Building extension module rcca...
ninja: no work to do.
Loading extension module rcca...
19 19:00:50 PyTorch Version 1.1.0
19 19:00:51 WRN Missing key(s) in state_dict: layer3.12.bn1.num_batches_tracked, bn3.num_batches_tracked, layer3.10.bn3.num_batches_tracked, layer3.14.bn1.num_batches_tracked, layer3.20.bn1.num_batches_tracked, layer4.1.bn3.num_batches_tracked, layer3.1.bn3.num_batches_tracked, layer3.20.bn3.num_batches_tracked, layer3.11.bn1.num_batches_tracked, layer3.2.bn2.num_batches_tracked, layer3.9.bn3.num_batches_tracked, layer3.8.bn2.num_batches_tracked, layer3.17.bn1.num_batches_tracked, head.convb.1.num_batches_tracked, layer3.10.bn2.num_batches_tracked, layer3.18.bn2.num_batches_tracked, layer3.17.bn2.num_batches_tracked, layer2.3.bn1.num_batches_tracked, bn2.num_batches_tracked, layer3.9.bn2.num_batches_tracked, layer3.18.bn3.num_batches_tracked, layer3.19.bn2.num_batches_tracked, layer2.1.bn3.num_batches_tracked, layer1.2.bn1.num_batches_tracked, layer2.1.bn2.num_batches_tracked, layer3.3.bn1.num_batches_tracked, layer3.19.bn1.num_batches_tracked, layer1.0.bn1.num_batches_tracked, layer3.12.bn2.num_batches_tracked, layer3.5.bn3.num_batches_tracked, layer3.4.bn2.num_batches_tracked, layer3.0.bn1.num_batches_tracked, layer2.3.bn3.num_batches_tracked, layer3.5.bn1.num_batches_tracked, layer2.1.bn1.num_batches_tracked, layer3.9.bn1.num_batches_tracked, layer4.0.bn1.num_batches_tracked, layer2.0.downsample.1.num_batches_tracked, layer3.3.bn3.num_batches_tracked, layer2.2.bn2.num_batches_tracked, layer3.15.bn1.num_batches_tracked, layer4.0.bn2.num_batches_tracked, layer3.7.bn3.num_batches_tracked, layer3.12.bn3.num_batches_tracked, layer3.22.bn2.num_batches_tracked, layer1.0.downsample.1.num_batches_tracked, bn1.num_batches_tracked, layer1.0.bn3.num_batches_tracked, layer3.6.bn1.num_batches_tracked, layer3.21.bn3.num_batches_tracked, layer4.2.bn1.num_batches_tracked, layer3.5.bn2.num_batches_tracked, layer4.1.bn2.num_batches_tracked, layer4.2.bn2.num_batches_tracked, layer3.6.bn3.num_batches_tracked, layer3.16.bn1.num_batches_tracked, layer1.1.bn3.num_batches_tracked, layer4.0.bn3.num_batches_tracked, layer3.1.bn2.num_batches_tracked, layer2.3.bn2.num_batches_tracked, layer3.1.bn1.num_batches_tracked, layer1.1.bn1.num_batches_tracked, layer3.21.bn1.num_batches_tracked, layer3.6.bn2.num_batches_tracked, layer3.7.bn1.num_batches_tracked, layer3.19.bn3.num_batches_tracked, layer3.22.bn1.num_batches_tracked, layer3.4.bn1.num_batches_tracked, head.conva.1.num_batches_tracked, layer4.1.bn1.num_batches_tracked, layer3.0.bn3.num_batches_tracked, layer1.2.bn2.num_batches_tracked, layer3.11.bn3.num_batches_tracked, layer2.0.bn3.num_batches_tracked, layer2.0.bn1.num_batches_tracked, layer3.10.bn1.num_batches_tracked, layer3.18.bn1.num_batches_tracked, layer4.0.downsample.1.num_batches_tracked, layer1.2.bn3.num_batches_tracked, layer2.2.bn3.num_batches_tracked, layer3.13.bn3.num_batches_tracked, layer3.13.bn1.num_batches_tracked, layer3.0.bn2.num_batches_tracked, layer3.7.bn2.num_batches_tracked, layer3.20.bn2.num_batches_tracked, layer3.22.bn3.num_batches_tracked, layer1.0.bn2.num_batches_tracked, layer3.15.bn3.num_batches_tracked, layer3.3.bn2.num_batches_tracked, layer2.0.bn2.num_batches_tracked, layer3.4.bn3.num_batches_tracked, layer3.16.bn3.num_batches_tracked, layer3.8.bn1.num_batches_tracked, layer3.17.bn3.num_batches_tracked, layer3.16.bn2.num_batches_tracked, layer3.15.bn2.num_batches_tracked, dsn.1.num_batches_tracked, layer3.8.bn3.num_batches_tracked, layer4.2.bn3.num_batches_tracked, layer3.21.bn2.num_batches_tracked, layer2.2.bn1.num_batches_tracked, layer3.14.bn3.num_batches_tracked, layer3.2.bn1.num_batches_tracked, layer3.14.bn2.num_batches_tracked, layer3.2.bn3.num_batches_tracked, layer3.13.bn2.num_batches_tracked, head.bottleneck.1.num_batches_tracked, layer1.1.bn2.num_batches_tracked, layer3.0.downsample.1.num_batches_tracked, layer3.11.bn2.num_batches_tracked
19 19:00:51 Load model, Time usage:
	IO: 0.10071992874145508, initialize parameters: 0.09806418418884277
500 images are loaded!
[00:08<?,?it/s]
19 19:01:00 WRN A exception occurred during Engine initialization, give up running process
Traceback (most recent call last):
  File "evaluate.py", line 284, in <module>
    main()
  File "evaluate.py", line 247, in main
    output = predict_multiscale(model, image, input_size, [1.0], args.num_classes, False, 0)
  File "evaluate.py", line 168, in predict_multiscale
    scaled_probs = predict_sliding(net, scale_image, tile_size, classes, recurrence)
  File "evaluate.py", line 130, in predict_sliding
    padded_prediction = net(torch.from_numpy(padded_img).cuda(non_blocking=True))
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/monica/DATA/documenti/Monica/vos_approaches/CCNet/networks/ccnet.py", line 176, in forward
    x = self.relu1(self.bn1(self.conv1(x)))
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/inplace_abn/abn.py", line 323, in forward
    self.group,
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/inplace_abn/functions.py", line 307, in inplace_abn_sync
    group,
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/inplace_abn/functions.py", line 91, in forward
    ctx.world_size = distributed.get_world_size(group=group)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 584, in get_world_size
    return _get_group_size(group)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 200, in _get_group_size
    _check_default_pg()
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 191, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
Traceback (most recent call last):
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/monica/miniconda3/envs/ccnet/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/monica/miniconda3/envs/ccnet/bin/python', '-u', 'evaluate.py', '--local_rank=0', '--data-dir', '/media/monica/DATA/documenti/Monica/datasetOnline/cityscapes/', '--model', 'ccnet', '--input-size', '769,769', '--batch-size', '4', '--restore-from', 'snapshots/CS_scenes_60000-r1-77.9.pth', '--gpu', '0']' returned non-zero exit status 1.
```

Where is the problem? Can anyone help me?

**Comment by speedinghzl** [comment]
@gruossomonica  The inplace-abn does not support evaluation on one GPU.  Please refer to [here](https://github.com/mapillary/inplace_abn/issues/131).

**Comment by gruossomonica** [comment]
Thanks for replying to me. Since there is currently no solution, I close the issue.
