### ISSUE TITLE
Error while running run_local.sh

### ISSUE THREAD

**Issue by shrutishrestha** [speedinghzl/CCNet#96]
Hi I am having this problem while running I have built the build file by installing the setup.py, but while running the command 
"./run_local.sh YOUR_CS_PATH ccnet 60000 256,256 [0|1]". But I am geeting this error of   extra_cuda_cflags= ["--expt-extended-lambda"]). My log is printed here.

1]: command not found
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from networks.ccnet import ResNet
  File "/home/srutsth/PycharmProjects/PolypCCNet/networks/ccnet.py", line 11, in <module>
    from cc_attention.functions import CrissCrossAttention
  File "/home/srutsth/PycharmProjects/PolypCCNet/cc_attention/functions.py", line 20, in <module>
    extra_cuda_cflags= ["--expt-extended-lambda"])
  File "/home/srutsth/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 644, in load
    is_python_module)
  File "/home/srutsth/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 813, in _jit_compile
    with_cuda=with_cuda)
  File "/home/srutsth/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 847, in _write_ninja_file_and_build
    verbose)
  File "/home/srutsth/miniconda3/envs/myenv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 904, in _prepare_ldflags
    print('Detected CUDA files, patching ldflags')

**Comment by speedinghzl** [comment]
Hi @shrutishrestha  Maybe the new branch [pure-python](https://github.com/speedinghzl/CCNet/tree/pure-python) could solve the problem. It's a pure python implementation of CCNet and it does not need to be compiled with CUDA.

**Comment by johndpope** [comment]
When I run the pure-python branch - I get 
```

 ./run_local.sh          
Linux pop-os 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
Sun 07 Feb 2021 21:03:08 AEDT
Traceback (most recent call last):
  File "train.py", line 16, in <module>
    from networks.ccnet import Res_Deeplab
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/networks/ccnet.py", line 15, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/_ext/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
Traceback (most recent call last):
  File "evaluate.py", line 14, in <module>
    from networks.ccnet import Res_Deeplab
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/networks/ccnet.py", line 15, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/jp/Documents/gitWorkspace/CCNet-pure/libs/_ext/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

```

was hoping this branch would solve - but unfortunately problem persists.
https://github.com/Serge-weihao/CCNet-Pure-Pytorch/issues/9

**Comment by speedinghzl** [comment]
@johndpope Thanks for your reply.  I recently have updated the [pure-python branch](https://github.com/speedinghzl/CCNet/tree/pure-python).
